Repository valheimPlus/ValheimPlus, pull requests merged in 2021-03, with the labels that each got.

#199 0.9.2 release
  README.md
  ValheimPlus/AdvancedBuildingMode.cs
  ValheimPlus/AdvancedEditingMode.cs
  ValheimPlus/Configurations/Configuration.cs
  ValheimPlus/Configurations/ConfigurationExtra.cs
  ValheimPlus/Configurations/Sections/MapConfiguration.cs
  ValheimPlus/Configurations/Sections/ServerConfiguration.cs
  ValheimPlus/Configurations/Sections/StaminaConfiguration.cs
  ValheimPlus/Configurations/Sections/WagonConfiguration.cs
  ValheimPlus/Experience.cs
  ValheimPlus/FejdStartup.cs
  ValheimPlus/GameClasses/Beehive.cs
  ValheimPlus/GameClasses/Console.cs
  ValheimPlus/GameClasses/CraftingStation.cs
  ValheimPlus/GameClasses/EnvMan.cs
  ValheimPlus/GameClasses/FejdStartup.cs
  ValheimPlus/GameClasses/Fermenter.cs
  ValheimPlus/GameClasses/Fireplace.cs
  ValheimPlus/GameClasses/Game.cs
  ValheimPlus/GameClasses/GameCamera.cs
  ValheimPlus/GameClasses/Humanoid.cs
  ValheimPlus/GameClasses/Inventory.cs
  ValheimPlus/GameClasses/InventoryGUI.cs
  ValheimPlus/GameClasses/ItemDrop.cs
  ValheimPlus/GameClasses/Minimap.cs
  ValheimPlus/GameClasses/Player.cs
  ValheimPlus/GameClasses/Skills.cs
  ValheimPlus/GameClasses/Smelter.cs
  ValheimPlus/GameClasses/SteamGameServer.cs
  ValheimPlus/GameClasses/Vagon.cs
  ValheimPlus/GameClasses/Version.cs
  ValheimPlus/GameClasses/Ward.cs
  ValheimPlus/GameClasses/WearNTear.cs
  ValheimPlus/GameClasses/ZDOMan.cs
  ValheimPlus/GameClasses/ZNet.cs
  ValheimPlus/Hud.cs
  ValheimPlus/Initialize.cs
  ValheimPlus/Items.cs
  ValheimPlus/Player.cs
  ValheimPlus/PlayerDodgeRoll.cs
  ValheimPlus/PlayerStats.cs
  ValheimPlus/Properties/AssemblyInfo.cs
  ValheimPlus/RPC/VPlusConfigSync.cs
  ValheimPlus/Server.cs
  ValheimPlus/Settings.cs
  ValheimPlus/Utility/Helper.cs
  ValheimPlus/ValheimPlus.csproj
  valheim_plus.cfg
Labels: pending merge

#149 Added Stamina Numerical UI
  ValheimPlus/Configurations/Sections/HudConfiguration.cs
  ValheimPlus/GameClasses/Hud.cs
  ValheimPlus/ValheimPlus.csproj
  valheim_plus.cfg
Labels: enhancement, pending merge

#166 fix #165
  README.md
Labels: pending merge

#197 Bug fix for HUD current items available #195
  ValheimPlus/GameClasses/InventoryGUI.cs
Labels: enhancement, pending merge

#172 Update Time logic to be aligned with configuration + update config (#154/#171)
  ValheimPlus/GameClasses/EnvMan.cs
  ValheimPlus/RPC/VPlusConfigSync.cs
  valheim_plus.cfg
Labels: enhancement, needs updating

#191 Fixes and additions to the StaminaUsage section
  README.md
  ValheimPlus/Configurations/Sections/StaminaUsageConfiguration.cs
  ValheimPlus/GameClasses/Player.cs
  valheim_plus.cfg
Labels: enhancement, pending merge

#38 Simplify project setup
  README.md
  ValheimPlus/ValheimPlus.csproj
Labels: enhancement, pending merge

#161 add unix start scripts, add LGSM instructions to README
  .gitattributes
  README.md
  ValheimPlus.sln
  resources/unix/start_game_bepinex.sh
  resources/unix/start_server_bepinex.sh
Labels: enhancement

#212 add ZNet extensions for instance scope determination
  ValheimPlus/Utility/ZNetExtensions.cs
  ValheimPlus/ValheimPlus.csproj
Labels: enhancement, needs updating

#217 Fixing invalid placement restriction
  ValheimPlus/GameClasses/EnvMan.cs
  ValheimPlus/GameClasses/Player.cs
Labels: bug

#208 Create CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#223 Inventory Overhaul v0.1
  README.md
  ValheimPlus/Configurations/Configuration.cs
  ValheimPlus/Configurations/Sections/InventoryConfiguration.cs
  ValheimPlus/GameClasses/Inventory.cs
  ValheimPlus/GameClasses/InventoryGUI.cs
  valheim_plus.cfg
Labels: enhancement, pending merge

#226 Removing tombstone note on readme
  README.md
Labels: bug

#227 Correction for stamina usage description
  valheim_plus.cfg
Labels: bug

#230 Added a "remove damage flash" function
  ValheimPlus/Configurations/Sections/HudConfiguration.cs
  ValheimPlus/GameClasses/Hud.cs
  valheim_plus.cfg
Labels: enhancement

#224 - Added Crop notifier when a player tries to place a crop too close t…
  ValheimPlus/Configurations/Sections/PlayerConfiguration.cs
  ValheimPlus/GameClasses/Player.cs
  valheim_plus.cfg
Labels: enhancement

#262 Updating cfg for clarification, fixing min and max for iron chest
  ValheimPlus/GameClasses/Inventory.cs
  valheim_plus.cfg
Labels: bug

#266 Update maximumWood configuration to reflect the games default value
  valheim_plus.cfg
Labels: bug, pending merge

#269 Fireplace update for clarity in cfg
  README.md
  ValheimPlus/Configurations/Configuration.cs
  ValheimPlus/Configurations/Sections/FireSourceConfiguration.cs
  ValheimPlus/GameClasses/Fireplace.cs
  ValheimPlus/ValheimPlus.csproj
  valheim_plus.cfg
Labels: bug, enhancement

#286 Addressing cfg "opposite enforceMod" bug
  ValheimPlus/GameClasses/Console.cs
  ValheimPlus/GameClasses/Version.cs
  ValheimPlus/RPC/VPlusConfigSync.cs
Labels: bug

#285 Restricting smelter changes to furnace and kiln only
  ValheimPlus/GameClasses/Player.cs
  ValheimPlus/GameClasses/Smelter.cs
Labels: bug

#248 Add the ability to remember the mouse position when it loses focus
  README.md
  ValheimPlus/Configurations/Sections/HudConfiguration.cs
  ValheimPlus/GameClasses/GameCamera.cs
  valheim_plus.cfg
Labels: enhancement, pending merge

#291 Fixing ABM immediate exit bug
  ValheimPlus/AdvancedBuildingMode.cs
  ValheimPlus/GameClasses/Attack.cs
  ValheimPlus/GameClasses/Player.cs
  ValheimPlus/ValheimPlus.csproj
Labels: bug

#309 Deconstruct feature
  README.md
  ValheimPlus/Configurations/Configuration.cs
  ValheimPlus/Configurations/Sections/DeconstructConfiguration.cs
  ValheimPlus/Deconstruct.cs
  ValheimPlus/GameClasses/InventoryGUI.cs
  ValheimPlus/GameClasses/Player.cs
  ValheimPlus/ValheimPlus.csproj
  valheim_plus.cfg
Labels: enhancement, pending merge

#300 Added a number of new build-related features.
  ValheimPlus/Configurations/Sections/BuildingConfiguration.cs
  ValheimPlus/Configurations/Sections/WorkbenchConfiguration.cs
  ValheimPlus/GameClasses/Piece.cs
  ValheimPlus/GameClasses/Player.cs
  ValheimPlus/GameClasses/StationExtension.cs
  ValheimPlus/ValheimPlus.csproj
  valheim_plus.cfg
Labels: enhancement, needs updating, pending merge

#301 Food changes.
  ValheimPlus/Configurations/Sections/FoodConfiguration.cs
  ValheimPlus/GameClasses/Player.cs
  valheim_plus.cfg
Labels: enhancement

#303 Added a number of QoL changes.
  ValheimPlus/Configurations/Sections/BuildingConfiguration.cs
  ValheimPlus/Configurations/Sections/PlayerConfiguration.cs
  ValheimPlus/GameClasses/SE_Rested.cs
  ValheimPlus/GameClasses/Skills.cs
  ValheimPlus/ValheimPlus.csproj
  valheim_plus.cfg
Labels: enhancement

#314 Map Sync
  README.md
  ValheimPlus/AdvancedEditingMode.cs
  ValheimPlus/Configurations/ConfigurationExtra.cs
  ValheimPlus/GameClasses/Beehive.cs
  ValheimPlus/GameClasses/Console.cs
  ValheimPlus/GameClasses/CraftingStation.cs
  ValheimPlus/GameClasses/EnvMan.cs
  ValheimPlus/GameClasses/FejdStartup.cs
  ValheimPlus/GameClasses/Fermenter.cs
  ValheimPlus/GameClasses/Fireplace.cs
  ValheimPlus/GameClasses/Game.cs
  ValheimPlus/GameClasses/GameCamera.cs
  ValheimPlus/GameClasses/Humanoid.cs
  ValheimPlus/GameClasses/Inventory.cs
  ValheimPlus/GameClasses/InventoryGUI.cs
  ValheimPlus/GameClasses/ItemDrop.cs
  ValheimPlus/GameClasses/Minimap.cs
  ValheimPlus/GameClasses/Player.cs
  ValheimPlus/GameClasses/Skills.cs
  ValheimPlus/GameClasses/Smelter.cs
  ValheimPlus/GameClasses/SteamGameServer.cs
  ValheimPlus/GameClasses/Vagon.cs
  ValheimPlus/GameClasses/Version.cs
  ValheimPlus/GameClasses/Ward.cs
  ValheimPlus/GameClasses/WearNTear.cs
  ValheimPlus/GameClasses/ZDOMan.cs
  ValheimPlus/GameClasses/ZNet.cs
  ValheimPlus/RPC/VPlusAck.cs
  ValheimPlus/RPC/VPlusConfigSync.cs
  ValheimPlus/RPC/VPlusMapSync.cs
  ValheimPlus/Settings.cs
  ValheimPlus/UI/VPlusMainMenu.cs
  ValheimPlus/Utility/EmbeddedAsset.cs
  ValheimPlus/Utility/Helper.cs
  ValheimPlus/Utility/ListExtensions.cs
  ValheimPlus/Utility/RPCQueue.cs
  ValheimPlus/Utility/ZPackageExtensions.cs
  ValheimPlus/VPlusDataObjects.cs
  ValheimPlus/ValheimPlus.cs
  ValheimPlus/ValheimPlus.csproj
  ValheimPlus/ValheimPlus.csproj.user
  resources/tools/pdb2mdb.exe
  valheim_plus.cfg
Labels: enhancement

#319 Revert "Add the ability to remember the mouse position when it loses focus"
  README.md
  ValheimPlus/Configurations/Sections/HudConfiguration.cs
  ValheimPlus/GameClasses/GameCamera.cs
  valheim_plus.cfg
Labels: bug

#320 Repairs merge issues from Map Sync and allows build
  ValheimPlus/GameClasses/Player.cs
  ValheimPlus/Utility/Helper.cs
Labels: bug

#321 Fixing deconstruct button persistence
  ValheimPlus/Deconstruct.cs
  ValheimPlus/GameClasses/InventoryGUI.cs
Labels: bug

#322 Update README.md
  README.md
Labels: documentation

#344 Fix for null ref with map sync disabled
  ValheimPlus/GameClasses/Minimap.cs
  ValheimPlus/GameClasses/ZNet.cs
Labels: bug

#378 Updating start_server_bepinex.sh for 0.9.5.5 fix
  resources/unix/start_server_bepinex.sh
Labels: still being discussed

#392 Add Auto Fuel feature
  ValheimPlus/Configurations/Sections/FireSourceConfiguration.cs
  ValheimPlus/Configurations/Sections/FurnaceConfiguration.cs
  ValheimPlus/Configurations/Sections/KilnConfiguration.cs
  ValheimPlus/Configurations/Sections/SmelterConfiguration.cs
  ValheimPlus/GameClasses/Beehive.cs
  ValheimPlus/GameClasses/Fireplace.cs
  ValheimPlus/GameClasses/Smelter.cs
  ValheimPlus/Utility/Helper.cs
  ValheimPlus/Utility/InventoryAssistant.cs
  valheim_plus.cfg
  vplusconfig.json
Labels: pending merge

#403 Allows players to craft from nearby containers
  ValheimPlus/Configurations/Configuration.cs
  ValheimPlus/Configurations/Sections/CraftFromChestConfiguration.cs
  ValheimPlus/GameClasses/Container.cs
  ValheimPlus/GameClasses/CookingStation.cs
  ValheimPlus/GameClasses/Fireplace.cs
  ValheimPlus/GameClasses/InventoryGUI.cs
  ValheimPlus/GameClasses/Player.cs
  ValheimPlus/Utility/InventoryAssistant.cs
  ValheimPlus/ValheimPlus.csproj
  valheim_plus.cfg
  vplusconfig.json
Labels: pending merge

#316 Merge items with existing stacks when picking up tombstone.
  ValheimPlus/Configurations/Sections/InventoryConfiguration.cs
  ValheimPlus/GameClasses/Inventory.cs
  valheim_plus.cfg
Labels: still being discussed

#459 Repaired formatting
  ValheimPlus/FirstPerson/VPlusFirstPerson.cs
Labels: pending merge

#443 Latest Feature Requests
  vplusFAQ/faq.json
  vplusSuggestions/todo.json
Labels: in progress

#408 Added projectile modification section, applies to bow and javelin
  README.md
  ValheimPlus/Configurations/Configuration.cs
  ValheimPlus/Configurations/Sections/MonsterProjectileConfiguration.cs
  ValheimPlus/Configurations/Sections/PlayerProjectileConfiguration.cs
  ValheimPlus/GameClasses/Attack.cs
  ValheimPlus/ValheimPlus.csproj
  valheim_plus.cfg
  vplusconfig.json
Labels: in progress, merge conflicts, pending merge

#494 Allow modifiying Pickable yield
  ValheimPlus/Configurations/Configuration.cs
  ValheimPlus/Configurations/Sections/PickableConfiguration.cs
  ValheimPlus/GameClasses/Pickable.cs
  ValheimPlus/ValheimPlus.csproj
  valheim_plus.cfg
  vplusSuggestions/todo.json
  vplusconfig.json
Labels: in progress, pending merge
